In [55]:
! pip install numpy 

# NumPy

# 1. 넘파이 개요

## 1.1 넘파이 배열 생성해보기 

In [56]:
import numpy as np

arr = np.array([0,1,2,3,4,5,6,7,8,9,10])

print(type(arr))

<class 'numpy.ndarray'>


In [57]:
arr2 = np.eye(3)
print(type(arr2))
arr2

<class 'numpy.ndarray'>


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
arr3 = np.eye(4,5)

print(type(arr3))
arr3

<class 'numpy.ndarray'>


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

## 1.2 행렬 합 연산 비교 

In [59]:
matrix_1 = [[1,2],[3,4]]
matrix_2 = [[5,6],[7,8]]

#list 계산
matrix_result = []

for i in range(len(matrix_1)):
    tmp = []
    for j in range(len(matrix_2)):
        tmp.append(matrix_1[i][j]+matrix_2[j][i])

    matrix_result.append(tmp)

print(matrix_result)

[[6, 9], [9, 12]]


In [60]:
# numpy로 계산
matrix_result = np.array(matrix_1) + np.array(matrix_2)
matrix_result

array([[ 6,  8],
       [10, 12]])

# 2. 배열생성 1

## 2.1 배열 생성 

In [61]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

## 2.2 배열 모양 확인

In [62]:
arr.shape

(5,)

## 2.3 type 확인 

In [63]:
print(type(arr))

<class 'numpy.ndarray'>


## 2.4 모든 요소가 같은 자료형

In [64]:
arr_2 = np.array([0.1, 5, 4, 12, 0.5])
print(arr_2.dtype)
arr_2

float64


array([ 0.1,  5. ,  4. , 12. ,  0.5])

## 2.5 무한대 표현과 정의할 수 없는 숫자 표현 

- 무한대 표현: np.inf (infinity)
- 정의할 수 없는 숫자: np.nan (not a number)
- 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf가 나옴
- 0을 0으로 나누려고 시도하면 np.nan이 나옴


In [65]:
np.array([0,1,-1,0]) / np.array([1,0,0,0])

/var/folders/xl/7dlx2c2101l0npv7xr6d_x8w0000gn/T/ipykernel_49720/1032392073.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])
/var/folders/xl/7dlx2c2101l0npv7xr6d_x8w0000gn/T/ipykernel_49720/1032392073.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

## 2.6 2차원 배열 생성

In [66]:
my_list = [[0,1,2],[3,4,5]]
arr = np.array([0,1,2][3,4,5])
arr

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/var/folders/xl/7dlx2c2101l0npv7xr6d_x8w0000gn/T/ipykernel_49720/1696486170.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  arr = np.array([0,1,2][3,4,5])
/var/folders/xl/7dlx2c2101l0npv7xr6d_x8w0000gn/T/ipykernel_49720/1696486170.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  arr = np.array([0,1,2][3,4,5])
/var/folders/xl/7dlx2c2101l0npv7xr6d_x8w0000gn/T/ipykernel_49720/1696486170.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  arr = np.array([0,1,2][3,4,5])


TypeError: list indices must be integers or slices, not tuple

## 2.7 3차원 배열 생성

In [ ]:
arr = np.array([[[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]],
                 [[13,14,15,16],
                  [17,18,19,20],
                  [21,22,23,24]]])

In [ ]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

## 2.8 배열의 차원과 크기 알아내기 

In [ ]:
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(2, 3, 4)
3
int64


## 2.9 배열생성 실습 01

[문제] 넘파이를 사용하여 다음과 같은 행렬을 만들어 보세요

[실행 결과] 
```
array([[10, 20, 30, 40],
    [50, 60, 70, 80]])
```

In [ ]:
import numpy as np
np.array([[_ for _ in range(20,41,20)],
          [_ for _ in range(50,81,10)]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80]])
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 2.10 배열생성 실습 02

[문제]
- 1~18의 값을 가지는 shape이 (3, 2, 3) ndarray를 만들어 봅시다.
- 단, 자료형은 실수로 합니다. 

[실행 결과]
```
array([[[1., 2., 3.],
    [4., 5., 6.,]],
    [[7., 8., 9.,],
        [10., 11., 12.]],
    [[13., 14., 15.],
        [16., 17., 18.]]])
```

In [ ]:
data = []

for i in range(3):
    group = []
    for j in range(2):
        row = []
        for k in range(3):
            value = float(k + j*3 + i*6 +1)
            row.append(value)
        group.append(row)
    data.append(group)
print(data)

[[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]], [[13.0, 14.0, 15.0], [16.0, 17.0, 18.0]]]


In [ ]:
arr = np.array([[[1., 2., 3.],
                 [4., 5., 6.,]],
                [[7., 8., 9.,],
                 [10., 11., 12.]],
                [[13., 14., 15.],
                 [16., 17., 18.]]])
arr

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]])

# 3. 벡터화 연산 

## 3.1 벡터화 연산

In [ ]:
data = [0,1,2,3,4,5,6,7,8,9]

answer = [2*d for d in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
answer = np.array(data)*2
answer  

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(2*a+b)

[12 24 36]


## 3.2 벡터화 연산 실습 01

[문제] \
array([[1, 2, 3], [4, 5, 6]])과 array([[7, 8, 9], [10, 11, 12]])를 만들고 이 두 넘파이 배열을 활용하여아래의 계산 결과를 구해보세요.


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([_ for _ in range(1,10)])

print(a*3)
print(b*3)

[ 3  6  9 12 15 18 21 24 27]
[ 3  6  9 12 15 18 21 24 27]


## 3.3 벡터화 연산 실습 02

[문제]  
- 1부터 9까지 정수 값을 갖는 1차원 ndarray를 생성하세요.
- 그리고 그 ndarray를 활용항 3부터 27까지의 3배수를 갖는 ndarray를 출력해보세요.


# 4. 배열의 인덱싱과 슬라이싱 

## 4.1 print와 display 차이 살펴보기

In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[10, 20, 30], [40, 50, 60], [70, 80, 90]]])

b = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[10, 20, 30], [40, 50, 60], [70, 80, 90]]])

print(a,b)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]] [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [ ]:
print(a,b, sep='\n\n')

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [ ]:
display('안녕\n하세요.')
print('안녕\n하세요.')

'안녕\n하세요.'

안녕
하세요.


In [ ]:
! pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 34.4 MB/s eta 0:00:00 0:00:01


In [ ]:
import pandas as pd

# 간단한 DataFrame 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)

# DataFrame 출력
print(df)
df
display(df)
# df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Diana   28      Houston


Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Diana   28      Houston

## 4.2 배열의 인덱싱

### 4.2.1 1차원 배열 인덱싱

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

print(a[1,2])
print(a[0,1])
print(a[1,1])

6
2
5


### 4.2.2 다차원 배열 인덱싱

1. 2차원 배열

2. 3차원 배열

In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
	[[10, 20, 30], [40, 50, 60], [70, 80, 90]]])

In [ ]:
print(a[0,2])
print(a[0][2])
a[0][2]

[7 8 9]
[7 8 9]


array([7, 8, 9])

In [ ]:
print(a[1,1,2])

60


In [ ]:
a=np.array([[0,1,2],[3,4,5]])
display(a)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
print(a[1, :])

[3 4 5]


## 4.3 배열 슬라이싱

1. 2차원 배열 슬라이싱

2. 3차원 배열 슬라이싱

3. 증감을 표현하는 슬라이싱

## 4.4 슬라이싱 실습 01

[문제] 주어진 행렬에 대하여 각 문제를 해결해보세요.
- 값 7 인덱싱
- 값 14 인덱싱
- 배열 [6, 7] 슬라이싱
- 배열 [7, 12] 슬라이싱
- 배열 [[3, 4], [8, 9]]


## 4.5 슬라이싱 실습 02

[문제] 주어진 행렬에 대하여 각 문제를 해결해보세요.
\
\
array([[[  1,   2,   3], \
        [  4,   5,   6], \
        [  7,   8,   9]], \
 \
       [[ 10,  20,  30], \
        [ 40,  50,  60], \
        [ 70,  80,  90]], \
\
       [[100, 200, 300], \
        [400, 500, 600], \
        [700, 800, 900]]])
        

## 02 배열 생성

## 02-1

[문제 1] 아래와 같은 배열을 출력하세요
\
\
array([[2, 5, 8], \
    [20, 50, 80], \
    [200, 500, 800]])


## 02-2

[문제 2] 아래와 같은 배열을 출력하세요
\
\
array([[1, 3], \
    [100, 300]])


## 02-3

[문제 2] 아래와 같은 배열을 출력하세요
\
\
array([[[3, 2, 1], \
    [9, 8, 7]], \
\
    [[30, 20, 10], \
    [90, 80, 70]]])


# 5. 배열생성 2

## 5.1 zeros

In [ ]:
c = np.zeros((5,2))
c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
c.dtype

dtype('float64')

In [ ]:
c.shape

(5, 2)

In [ ]:
c_ = np.zeros ((5,2), dtype = 'i')
c_

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

## 5.2 ones

In [ ]:
e= np.ones((2,3,4))
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
e.shape

(2, 3, 4)

In [ ]:
e.dtype

dtype('float64')

## 5.3 zeros_like, ones_like

## 배열생성2 실습 01

[문제] 빈 문자열을 갖는 shape이 (3, 3, 3) ndarray를 만들어 봅시다.
- 단, dtype은 ‘U10’으로 합니다.


## 배열생성2 실습 02
[문제] zeros/ones 함수를 사용해서 배열을 만들고 아래와 같은 배열을 만들어 보세요
\
\
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 배열생성2 실습 03
[문제] zeros/ones 함수를 사용해서 배열을 만들고 아래와 같은 배열을 만들어 보세요


## 5.4 empty

In [ ]:
h = np.empthy

## 5.5 arange

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 5.6 random

In [ ]:
# random.rand(size): 0~1 난수 생성

print(np.random.rand(3,3))

[[0.5563387  0.42235079 0.4329014 ]
 [0.10730133 0.82998453 0.16749749]
 [0.09614693 0.6255026  0.89703424]]


In [ ]:
# random.random(size): 0~1 난수 생성
#  size 를 튜플로 전달

print(np.random.random((3,3)))

[[0.34434016 0.97226327 0.87797266]
 [0.52163463 0.21452174 0.09968609]
 [0.34001572 0.47484175 0.95196679]]


## 5.7 linspace, logspace

In [ ]:
import numpy as np
arr = np.linspace(0, 100, 3)
arr

array([  0.,  50., 100.])

## 배열생성2 실습 04

[문제] linspace()를 활용하여 다음과 같은 1차원 ndarray를 만들어 보세요
\
\
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
arr = np.linspace(0.1, 0.9, 9)
arr

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

# 6. 배열 크기 변경

넘파이에서의 메타데이터와 데이터 버퍼

- 메타데이터: 데이터 자체를 변경하지 않고도, 데이터의 표현 방식 수정 가능
    - 데이터 형태: shape
    - dtype 
    - strides: 배열의 각 차원이 메모리에서 얼마나 떨어져있는지 (바이트 단위)
    - 메모리 읽기/쓰기 플래그: 배열이 읽기 전용인지 여부
    - 배열의 순서: 배열이 C-order(행 우선)인지 F-order(열 우선)인지 여부
    - 배열 객체 ID: 파이썬 수준에서 배열 객체를 구분하는 고유 메모리 주소 
- 데이터 버퍼 (Data Buffer)
    - 데이터 자체가 저장된 메모리 공간을 의미 (배열의 요소 값들이 연속적으로 저장됨)
        - 배열 데이터가 저장된 연속적인 메모리 블록의 시작 주소를 의미
    - NumPy 배열은 데이터를 C언어에서 사용하는 연속된 메모리 블록에 저장
    - __ array_interface __ ['data']를 통해 데이터 버퍼의 메모리 주소 확인 가능 
    - 버퍼에는 배열의 실제 데이터 값이 저장됨 
    - 특징
        - 배열의 요소는 데이터 버퍼에 저장 됨 (arr[0][0]은 버퍼의 특정 메모리 주소를 참조)
        - 데이터 공유: 뷰(view)배열은 원본 배열과 동일한 데이터 버퍼를 참조 -> 데이터 공유 가능 
        - 데이터는 일반적으로 연속적인 메모리 공간에 저장되며, strides를 통해 각 차원의 데이터 간 간격을 결정 

id와 __ array_interface __

- id()
    - 파이썬 자체의 고유 메모리 주소 반환
    - 객체의 컨테이너 또는 참조 수준에서 메모리 주소 확인 
    - 객체의 내부 데이터가 아닌 객체 자체에 대한 정보 제공
    - 객체가 같은 데이터를 공유하더라도 다른 ID를 가질 수 있음 (Numpy 배열에서 뷰(view)와 원본 배열의 경우)
    - arr과 view_arr의 id는 다름. 이는 배열의 메타데이터와 배열 객체가 독립적으로 존재하기 때문 

- __ array_interface __
    - Numpy 배열 객체가 관리하는 실제 데이터 버퍼의 정보 제공 
    - 데이터 버퍼 주소를 확인하는 데 유용하며, 원본 배열과 뷰(view)간에 데이터 공유 여부를 판단할 수 있음 
        - 두 배열의 데이터 버퍼 주소가 같다면, 같은 메모리를 참조하고 있음을 의미 
    - Numpy 배열의 내부 구조를 설명하는 속성 (attribute) -> 이 속성을 통해 배열의 데이터 버퍼 주소, dtype, strides 등을 알 수 있음 
    - 딕셔너리 형태이며 주요키는 아래와 같음
        - data: 배열이 참조하는 데이터 버퍼의 메모리 주소와 읽기/쓰기 플래그 반환
            - 읽기 쓰기 플래그: False(읽기 전용), True(읽기 쓰기 모두 가능) -> 하지만 객체수준에서만 적용됨 (데이터 버퍼는 해당 안 됨)
        - shape: 배열의 형태
        - strides: 데이터가 메모리에서 이동하는 간격 (바이트단위)
        - typestr: 배열의 데이터 타입 (dtype)
        - version: 인터페이스 버전 
    

## 6.1 reshape

In [ ]:
import numpy as np

a = np.arange(12)

print(id(a))
print(a.__array_interface__)
a

4505575536
{'data': (5351898544, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (12,), 'version': 3}


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(id(a.reshape(3, 4)))
print(a.reshape(3, 4).__array_interface__['data'][0])

4425564208
5351898544


In [ ]:
a_re = a.reshape(3,4)

# 배열확인
print(a)
print(a_re)

#각 개체의 id 주소 확인
print(id(a))
print(id(a_re))
print()


# reshape 객체의 base 확인
print(a_re.base)

# 데이터 범퍼 주소 확인
print(a.__array_interface__['data'][0])
print(a_re.__array_interface__['data'][0])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
4505575536
4505975664

[ 0  1  2  3  4  5  6  7  8  9 10 11]
5351898544
5351898544


In [ ]:
# -1을 활용한 배열 변경

test = a.reshape(3,-1)
test

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
test.shape

(3, 4)

In [ ]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

## 6.2 배열크기변경 실습 01

[문제] \
1부터 40가지의 짝수를 갖는 ndarray를 arange()로 만듭니다.\
그리고 shape을 변경하여 (2, 2, 5)로 변경해보세요.\
\
[2 4 6 8 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40] \
\
[결과] \
array([[[2, 4, 6, 8, 10], \
    [12, 14, 16, 18, 20], \
\
    [[22, 24, 26, 28, 30], \
    [32, 34, 36, 38, 40]]])



In [ ]:
a = np.arange(2, 41, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [ ]:
a.reshape(2,2,5)

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

## 6.3 flatten, ravel

### 6.3.1 flatten
- 깊은 복사

In [ ]:
# (3,4)

a = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11]])

a = np.arange(12)
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a_flatten = a.flatten()
print(a_flatten.shape)
a_flatten

(12,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# a의 첫 번째 요소 id
print(a[0][0])
print(id(a[0][0]))
print(a.__array_interface__['data'])
print()

# flatten 후의 첫 번쨰 요소 id 확인
print(a_flatten[0])
print(id(a_flatten[0]))
print(a_flatten.__array_interface__['data'])


0
4505465488
(4544916256, False)

0
4505465488
(4546680800, False)


In [ ]:
# 요소변경 -> 두 객체가 다 변경이 되지 않음 (깊은 복사라서)

print(a_flatten[0])
a_flatten[0]
print(0)

# 변경된 array 확인
print(a)
print()
print(a_flatten)



0
0
<built-in method ravel of numpy.ndarray object at 0x10c9dd890>

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### 6.3.2 ravel
- 얕은 복사

In [ ]:
a_ravel = a.ravel
print(a_ravel.shape)
a_ravel

AttributeError: 'builtin_function_or_method' object has no attribute 'ravel'

In [ ]:
#id
print(id(a))
print(id(a_ravel))
print()

#  0번째 요소 id
print(id[0][0])
print(id(a_ravel[0]))
print()

#  버퍼
print(a.__array_interface__['data'])
print(a_ravel.__array_interface__['data'])

4506638480
4507577744



TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
#0번째 요소 100으로 변경

# 변경 전 값 확인
print(a[0][0])
print(a_ravel[0][0])
print(a.__array_interface__['data'])
print(a_ravel.__array_interface__['data'])
print()

# 요소변경
a_ravel[0]

# qusrud gn rkqt ghkrdls
print(a)
print(a_ravel)

---
예제

In [ ]:
import numpy as np
# 원본 배열 생성
arr = np.array ([[1,2],[3,4]])

# arr 의 뷰(view) 생성
arr_view = arr.ravel()

# 뷰를 수정하면 원본도 변경됨
arr_view[0] = 99

print(arr)
print(arr_view)
print()

print(id(arr))
print(id(arr_view))
print(id(arr[0][0]))
print(id(arr_view[0]))
print()

# 실제 데이터 주소 비교 (바퍼 비교)
print(arr.__array_interface__['data'][0])
print(arr_view.__array_interface__['data'][0])

[[99  2]
 [ 3  4]]
[99  2  3  4]

4508203600
4508100304
4507132240
4507125968

5351854560
5351854560


In [6]:
import numpy as np
# 원본 배열 생성
arr = np.array ([[1,2],[3,4]])

# arr 의 뷰(view) 생성
arr_2 = arr.flattenl()

# flatten
arr_2[0] = 99

print(arr)
print(arr_view)
print()

print(id(arr))
print(id(arr_view))
print(id(arr[0][0]))
print(id(arr_view[0]))
print()

# 실제 데이터 주소 비교 (바퍼 비교)
print(arr.__array_interface__['data'][0])
print(arr_view.__array_interface__['data'][0])

AttributeError: 'numpy.ndarray' object has no attribute 'flattenl'

## 6.4 newaxis
- 인덱싱 기법으로 배열의 차원을 늘리는 데 유용

In [7]:
# 1차원 배열 생성
a = np.arange(12)

print(a.shape, a.ndim)

a

(12,) 1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
# 차원 증가
a = a[:, np.newaxis]   #  새로운 축 추가 : 모든 행은 유지하면서 새로운 열 차원을 추가
print(a.shape, a.ndim)
a



(12, 1) 2


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

## 6.5 전치 

In [9]:
a= np.array([[1,2,3],[4,5,6]])
print(a.shape, a.ndim)
a

(2, 3) 2


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 전치
b = a.T
print(b.shape, b.ndim)
b

(3, 2) 2


array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
print(id(a))
print(id(b))
print(a.__array_interface__['data'])
print(b.__array_interface__['data'])

4473175280
4473694096
(5476913648, False)
(5476913648, False)


## 6.6 배열 결합

### 6.6.1 hstack
배열을 수평으로 연결 

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,20,30],[40,50,60]])

print(a.shape,b.shape)
print() 
print(a)
print()
print(b)

(2, 3) (2, 3)

[[1 2 3]
 [4 5 6]]

[[10 20 30]
 [40 50 60]]


In [ ]:
c_vstack = np.hstack([a,b])
print(c_vstack.shape)
c_vstack


(2, 6)


array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

### 6.6.2 vstack
배열을 수직으로 연결 

In [14]:
c_vstack = np.vstack([a,b])
print(c.vstack.shape)
c_vstack

NameError: name 'c' is not defined

# 7. 브로드캐스팅

In [17]:
import numpy as np
a = np.array([1,2,3])
b= np.array([[10],[20],[30]])

print(a.shape, b.shape)

(3,) (3, 1)


In [18]:
result = a+b
print(result.shape)
result

(3, 3)


array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [20]:
c = a * b
print(c)

c.shape

[[ 10  40  90]
 [ 40 100 180]]


(2, 3)

In [21]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
print(a.shape. b.shape)

AttributeError: 'tuple' object has no attribute 'b'

In [ ]:
result = a * b
print(result.shape)
result

# 8. NumPy의 다양한 메서드 

In [22]:
a = np.array([[1,2,3],[4,5,6]])

## 8.1 최대/최소

In [25]:
# 최대
print(a.max())
# 최소
print(a.min())

# 최대값 인덱스
print(a.argmax())

6
1
5


## 8.1.1 argmax, argmin
- argmax: 해당 배열의 제일 큰 값의 인덱스 반환
- argmin: 해당 배열의 제일 작은 값의 인덱스 반환 

In [29]:
arr = np.reshape(np.random.randint(100,size=(12)), (2,3,-1) )
display(arr)

print()
print(np.argmax(arr))   # 축을 설정하지 않으면 1차원으로 생각했을 때의 인덱스 값을 반환
print(np.argmin(arr))
print()

print(arr.flatten()[np.argmax(arr)])
print(arr.flatten()[np.argmin(arr)])

array([[[10, 41],
        [98, 87],
        [44, 71]],

       [[94, 16],
        [88,  6],
        [ 9, 46]]])


2
9

98
6


In [ ]:
# 축을 설정 했을 경우 (axis를 설정했을 경우)
np. random.seed(1)

arr = np.reshape(np.random,randint(100,size)   )

In [ ]:
# (2,3,2,2)

print(np.argmax(arr,axis=0))   # (3,2,2)를 비교했을 떄 더 큰 값이 존재하는 배열의 인덱스로 반환
print( '-'* 20 )

print(np.argmax(arr,axis=1))
print( '-'* 20 )

print(np.argmax(arr,axis=2))
print( '-'* 20 )


[[1 0]
 [0 0]
 [0 0]]
--------------------
[[1 1]
 [0 2]]
--------------------
[[1 0 1]
 [0 0 1]]
--------------------


## 8.2 통계

In [31]:
# 합
print(a.sum())
print(np.sum(a))

21
21


In [32]:
# 평균
print(a.mean())
print(np.mean(a))

3.5
3.5


In [34]:
# 중의값
print(np.median(a))

3.5


In [35]:
# 표준편차
print(a.std())
print(np.std(a))

1.707825127659933
1.707825127659933


In [ ]:
# 분산
print(a.var())
print(np.var(a))

## 8.3 불리언

### 8.3.1 all()

In [ ]:
a= np.zeros(3,dtype=int)
b = np.ones(3,dtype=int)
c= arrays

### 8.3.2 any()

## 8.4 NumPy의 다양한 메서드 실습 01

[문제] 1부터 100까지의 3의 배수를 갖는 1차원 ndarray를 생성하고 그 전체의 합을 구하세요

## 8.5 NumPy의 다양한 메서드 실습 02

[문제] 
- 서버 응답시간의 데이터가 다음과 같이 존재합니다.
- 해당 값의 단위는 ms 입니다.
- 이 때 200ms를 넘기는 값의 개수가 총 몇개인지 구해보세요


# 9. 정렬

In [37]:
np.random.seed(2)
arr = np.reshape(np.random.randint(20,size=12), (3,-1))
arr

array([[ 8, 15, 13,  8],
       [11, 18, 11,  8],
       [ 7,  2, 17, 11]])

In [38]:
print(np.sort(arr,axis=0))

[[ 7  2 11  8]
 [ 8 15 13  8]
 [11 18 17 11]]


In [39]:
print(np.sort(arr,axis=1))

[[ 8  8 13 15]
 [ 8 11 11 18]
 [ 2  7 11 17]]
